### PR TITLE
Tunnel Relay v2

### PR DESCRIPTION
**Pull request by RamjotSingh**
#### What is being done?
Service Bus team recently released support for HTTP over HybridConnections. This allows for TunnelRelay to be usable across different OSes as we no longer need to depend on WCF. This PR re-architects the core of TunnelRelay and does the following

- Use HybridConnection instead of WCF relays
- Shift TunnelRelay core NetFramework to NetStandard 2.0
- Extend TunnelRelay to be pluggable in different UIs, Server etc. Full support for Dependency Injection

#### Backward Compatibility?
Sadly, this PR breaks backward compatibility. Turns out existing Service bus namespaces can't be used with Hybrid Connection. Also TunnelRelay Plugins dll is based on NetStandard now. This might require recompile for existing plugins. The interface however is left untouched.

#### Other additions
Added console mode, which allows TunnelRelay to be run in a console instead of GUI.

#### Requirements for TunnelRelay v2
Tunnel Relay v2 is written on top of .NetCore3.1 and thus follows the same requirements.

### CODE REVIEW

**Comment by rjmiller-revint** [comment]
Is this PR ever going to be approved?  I would like to try the new version but I don't really want to build from scratch either.

**Comment by RamjotSingh** [comment]
@rjmiller-revint Sorry I completely missed someone commented. I am planning to merge this one over next few days. I just need to sort a few things out before this PR can be merged.

**Comment by RamjotSingh** [comment]
@rjmiller-revint Alpha release bits are out. I have tested them, but they are marked alpha till this PR gets merged in.

**Comment by codeputer** [comment]
I'm really interested using this as  a means to route traffic to my local workstation.  this includes all kinds of public webhooks, including Twilio.  Never before contributed to an open source project, this may be the one!   I'm wondering if we should leverage services like the Hybrid Connection Manager in the design/architecture of the solution.  What we need is a cloud based reverse proxy that can route to a local/on-premise environment.  The issue with using the relay, was it needs to be coupled with a reverse proxy when a request is received from the subscription.  Is there an extension point in the pipeline to handle this?

The previous version used WCF Relay, and my first attempt was to use a WCF Routing.  That failed because of how the HTTP protocol was managed - POST worked, but GET Failed (as the Routing mechanism validated the GET request, and noticed that it had a payload.   Clemens reviewed this, and simply indicated that it was how the relay handled transport agnostic issues.  WCF as we all know didn't handle HTTP well, and although beautifully designed, in the end, was just too complex and the learning curve basically killed it.

**Comment by RamjotSingh** [comment]
@codeputer If I am getting your concern correctly you are concerned that if you were to run something behind TunnelRelay, there is still a component in the system which is receiving requests before you do and then throwing them at you instead of directly receiving them. 

Yes this is true. TunnelRelay is supposed to live as a standalone component and act as reverse proxy in the middle because the information being streamed over the websocket connect is not really HTTP pipeline decodable (for lack of a better explanation).

However I have 2 good news for you
1. As part of this PR I did remove the whole WCF pipeline (and thus allowing the expansion to non-Windows OSes)
2. This PR also shifts to using [Azure Relay Hybrid Connections](https://docs.microsoft.com/en-us/azure/service-bus-relay/relay-what-is-it)
3. As far as the sending payload in GET is concerned, it is something in code here which determines that GET requests with payload are not really valid and does not forward the body. I can look into reverting that and let the body work in GET as well.

Let me know if it answers your questions.

**Comment by RamjotSingh** [comment]
@codeputer Btw if you directly want to read requests from AzureRelay in your own server instead of sitting behind TunnelRelay you can look at https://www.nuget.org/packages/Microsoft.Azure.Relay.AspNetCore/1.1.0-preview-20180522-1

**Comment by AlmogCohen** [comment]
I'm looking for this one to be released! Thanks for the awesome work!

**Comment by RamjotSingh** [comment]
@AlmogCohen There are pre-release builds present on the Release page. Please check them out and report back if you find any issues. This PR is nearly done, no known issues from my side.

**Pull request merged**
